"""Implement a custom KernelSpecManager that finds kernels from EasyBuild's `jupyter-server` modules."""
import os
import re
import subprocess
import tempfile
from collections import defaultdict
from collections.abc import Mapping
from dataclasses import asdict, dataclass, field, fields
from functools import lru_cache

from jupyter_client.kernelspec import KernelSpec, KernelSpecManager, NoSuchKernel

from . import environment as env
from .loose_version import LooseVersion

STARTUP_TEMPLATE = """#!/bin/bash
# This script is generated by EasyBuild's Jupyter kernel spec manager.
# It is used to set up the environment for the kernel before starting it.
# Load the necessary modules
{module_loads}
# Start the kernel
exec {kernel_cmd} $@
"""


def module_cmd(cmd:str, init_module: str = '') -> str:
    """Run a module command and return the output."""
    cmd = f'module {cmd}'
    if init_module:
        cmd = f'module load {init_module} > /dev/null 2>&1 && {cmd}'
    try:
        output = subprocess.check_output(
            cmd,
            shell=True, executable='/bin/bash',
            stderr=subprocess.STDOUT
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Failed to execute module command `{cmd}`: {e.output.decode('utf-8')}") from e

    return output.decode('utf-8')

def module_avail(module_name: str, init_module: str = '') -> list[str]:
    """Return a list of available modules for a given module name using `module avail`."""
    res = module_cmd(f'--terse avail {module_name}/', init_module=init_module)

    res = res.splitlines()
    res = [line.strip() for line in res if line.strip()]
    res = list(filter(lambda module: not module.startswith('/'), res))

    return res

def simulate_module_load(module_name: str, init_module: str = '', depends_on=None) -> dict:
    """Minimally extract the environment variables that would be set by loading a module using `module show`."""
    setenvs = {}
    append_env = defaultdict(list)
    prepended_env = defaultdict(list)
    depends_on = set(depends_on or [])
    outputs = []

    main_load = module_cmd(f'show {module_name}', init_module=init_module)
    rgx = re.compile(r'depends_on\("([^"]+)"\)')
    done = set()
    found = []
    for match in rgx.finditer(main_load):
        value = match.group(1)
        found.append(value)
        for dep in (depends_on - done):
            if value.startswith(f'{dep}/'):
                done.add(dep)
                outputs.append(module_cmd(f'show {value}', init_module=init_module))
    if done != depends_on:
        missing = depends_on - done
        raise RuntimeError('\n  '.join([
            '',
            f"Failed to find all required dependencies for {module_name}: {missing}.",
            f"Found: {', '.join(found)}",
            'It is possible that the required modules are not direct dependencies of the main kernel module.'
        ]))

    outputs.append(main_load)
    for output in outputs:
        # Extract the values from the module show output
        # The output is expected to be in the format of 'setenv("VAR_NAME", "value")' for each environment variable
        rgx = re.compile(r'setenv\("([^"]+)",\s*"([^"]*)"\)')
        for match in rgx.finditer(output):
            setenvs[match.group(1)] = match.group(2)
        rgx = re.compile(r'prepend_path\("([^"]+)",\s*"([^"]*)"\)')
        for match in rgx.finditer(output):
            prepended_env[match.group(1)].insert(0, match.group(2))
        rgx = re.compile(r'append_path\("([^"]+)",\s*"([^"]*)"\)')
        for match in rgx.finditer(output):
            append_env[match.group(1)].append(match.group(2))

    for key in prepended_env:
        prepended_env[key] = os.pathsep.join(prepended_env[key])
    for key in append_env:
        append_env[key] = os.pathsep.join(append_env[key])

    return {
        'set': setenvs,
        'pre': prepended_env,
        'app': append_env,
    }

@dataclass
class ModuleKernelMapping(Mapping):
    """Map that hold information needed to build a `KernelData` instance from a specific module."""
    mod_name: str = field(metadata={
        'help': 'Name of the module (e.g., jupyter-server)',
    })
    kernel_display_name: str = field(metadata={
        'help': 'Display name of the kernel (e.g., Python 3)',
    })
    kernel_language: str = field(metadata={
        'help': 'Language of the kernel (e.g., python)',
    })
    kernel_path: str = field(metadata={
        'help': 'SH echo-able string that resolves to the path to the kernel spec directory',
    })
    launcher_exec: str = field(metadata={
        'help': 'Executable used to launch the kernel (e.g., python)',
    })
    launcher_args: tuple[str] = field(metadata={
        'help': 'Arguments to pass to the launcher executable',
    })
    launcher_version_env_var: str = field(metadata={
        'help': 'Environment variable that contains the launcher version to check from compatible loaded modules',
    })
    kernel_version_env_var: str = field(metadata={
        'help': 'Environment variable that contains the kernel version to be displayed',
    })
    launcher_version_filter: tuple[LooseVersion | str | None] = field(default=(None, None), metadata={
        'help': 'Tuple of [min_version, max_version) to filter out incompatible launcher versions',
    })
    launcher_args_env_vars: tuple[str] = field(default_factory=tuple, metadata={
        'help': 'Environment variables needed to resolve the launcher arguments (e.g., EBROOTIJULIA for IJulia)',
    })
    required_loads: tuple[str] = field(default_factory=tuple, metadata={
        'help': (
            'Modules that must be loaded also in lazy mode to ensure the initial environmenet variables are'
            'set correctly'
        ),
    })

    def __post_init__(self):
        self._hash = hash(tuple(sorted(self.items())))

    def __getitem__(self, key):
        """Allow dictionary-like access to the attributes of the dataclass."""
        return getattr(self, key)

    def __iter__(self):
        """Return an iterator over the attribute names of the dataclass."""
        return iter(asdict(self))

    def __len__(self):
        """Return the number of attributes in the dataclass."""
        return len(asdict(self))

    def __hash__(self):
        return self._hash

    def items(self):
        """Return a dictionary of the attributes of the dataclass."""
        return asdict(self).items()


# Map a module name to the kernel spec information. This is used to determine how to extract the necessary information
# from the environment module.
MODULE_KERNEL_MAP: dict[str, ModuleKernelMapping] = {
    'jupyter-server': ModuleKernelMapping(
        mod_name='jupyter-server',
        kernel_display_name='{display_prefix} Python',
        kernel_language='python',
        kernel_path='$EBROOTJUPYTERMINSERVER/share/jupyter/kernels/python3',
        launcher_exec='python',
        launcher_args=('-m', 'ipykernel_launcher', '-f'),
        launcher_version_env_var='EBVERSIONPYTHON',
        kernel_version_env_var='EBVERSIONPYTHON',
        required_loads=('Python',),
    ),
    'octave-kernel': ModuleKernelMapping(
        mod_name='octave-kernel',
        kernel_display_name='{display_prefix} Octave',
        kernel_language='octave',
        kernel_path='$EBROOTOCTAVEMINKERNEL/share/jupyter/kernels/octave/images',
        launcher_exec='python',
        launcher_args=('-m', 'octave_kernel', '-f'),
        launcher_version_env_var='EBVERSIONPYTHON',
        kernel_version_env_var='EBVERSIONOCTAVE',
        required_loads=('Python', 'Octave'),
    ),
    'IJulia_old': ModuleKernelMapping(
        mod_name='IJulia',
        kernel_display_name='{display_prefix} Julia',
        kernel_language='julia',
        kernel_path='$EBROOTIJULIA/jupyter/kernels/julia-*',
        launcher_exec='julia',
        launcher_args=(
            '-i', '--color=yes', '--project=@.', '$EBROOTIJULIA/packages/IJulia/src/kernel.jl'
        ),
        launcher_version_filter=(None, '1.11'),
        launcher_args_env_vars=('EBROOTIJULIA',),
        launcher_version_env_var='EBVERSIONJULIA',
        kernel_version_env_var='EBVERSIONJULIA',
        required_loads=('Julia',),
    ),
    'IJulia_new': ModuleKernelMapping(
        mod_name='IJulia',
        kernel_display_name='{display_prefix} Julia',
        kernel_language='julia',
        kernel_path='$EBROOTIJULIA/jupyter/kernels/julia-*',
        launcher_exec='julia',
        launcher_args=(
            '-i', '--color=yes', '--project=@.', '-e', '\'import IJulia; IJulia.run_kernel()\''
        ),
        launcher_version_filter=('1.11', None),
        launcher_version_env_var='EBVERSIONJULIA',
        kernel_version_env_var='EBVERSIONJULIA',
        required_loads=('Julia',),
    ),
    'root-kernel': ModuleKernelMapping(
        mod_name='root-kernel',
        kernel_display_name='{display_prefix} ROOT C++',
        kernel_language='c++',
        kernel_path='$EBROOTROOT/etc/notebook/kernels/root/',
        launcher_exec='python',
        launcher_args=('-m', 'JupyROOT.kernel.rootkernel', '-f'),
        launcher_version_env_var='EBVERSIONPYTHON',
        kernel_version_env_var='EBVERSIONROOT',
        required_loads=('Python', 'ROOT'),
    ),
    'IRkernel': ModuleKernelMapping(
        mod_name='IRkernel',
        kernel_display_name='{display_prefix} R',
        kernel_language='R',
        kernel_path='$EBROOTIRKERNEL/IRkernel/kernelspec/',
        launcher_exec='R',
        launcher_args=('--slave', '-e', '\'IRkernel::main()\'', '--args'),
        launcher_version_env_var='EBVERSIONR',
        kernel_version_env_var='EBVERSIONR',
        required_loads=('R',),
    ),
    'bash': ModuleKernelMapping(
        mod_name='jupyter-bash-kernel',
        kernel_display_name='{display_prefix} Bash',
        kernel_language='bash',
        kernel_path='$EBROOTJUPYTERMINBASHMINKERNEL/share/jupyter/kernels/bash',
        launcher_exec='python',
        launcher_args=('-m', 'bash_kernel', '-f'),
        launcher_version_env_var='EBVERSIONPYTHON',
        kernel_version_env_var='EBVERSIONJUPYTERMINBASHMINKERNEL',
        required_loads=('Python',),
    ),
}

CLING_CPP_STDS = ['11', '14', '17', '20', '2b', '1z']

MODULE_KERNEL_MAP.update({
    f'cling-{std}': ModuleKernelMapping(
        mod_name='cling-kernel',
        kernel_display_name=f'{{display_prefix}} C++{std} (Cling)',
        kernel_language='C++',
        kernel_path=f'$EBROOTCLINGMINKERNEL/share/jupyter/kernels/cling-cpp{std}',
        launcher_exec='jupyter-cling-kernel',
        launcher_args=(f'--std=c++{std}', '-f'),
        launcher_version_env_var='EBVERSIONCLING',
        kernel_version_env_var='EBVERSIONCLING',
        required_loads=('Cling',),
    ) for std in CLING_CPP_STDS
})

@dataclass
class KernelData:
    """Data class to hold information about a kernel spec derived from an EasyBuild module.
    The metadata for each field includes an help and an optional getcmd key, which is a shell command to retrieve the
    value of the field."""
    mod_name: str = field(metadata={
        'help': 'Module name',
    })
    mod_version: str = field(metadata={
        'help': 'Module version',
    })
    kernel_path: str = field(metadata={
        'help': 'Path to the kernel spec directory',
        'getcmd': 'realpath {kernel_path}'
    })
    kernel_version: str = field(metadata={
        'help': 'Kernel version',
        'getcmd': 'echo ${kernel_version_env_var}'
    })
    # launcher_exe: str = field(metadata={
    #     'help': 'Path to the Python executable',
    #     'getcmd': 'which {launcher_exec}'
    # })
    launcher_version: str = field(metadata={
        'help': 'Python version',
        'getcmd': 'echo ${launcher_version_env_var}'
    })
    launcher_args_env_vars: dict = field(default_factory=dict, metadata={
        'help': 'Environment variables needed to resolve the launcher arguments (e.g., EBROOTIJULIA for IJulia)',
    })
    init_module: str = field(default='', metadata={
        'help': 'Module that was loaded before the kernel module to initialize the environment',
    })

    @property
    def launcher_version_sem(self) -> LooseVersion:
        """Return the launcher version as a tuple of integers for semantic versioning comparison."""
        return LooseVersion(self.launcher_version)

    @classmethod
    @lru_cache(maxsize=None)
    def from_env_module(cls, module: str, info_map: ModuleKernelMapping, init_module: str = None) -> 'KernelData':
        """Create a KernelData instance from an environment module and a Mapping on how to extract its information."""
        data_dct = {}

        mod_name, mod_ver = module.split('/')

        data = simulate_module_load(module, init_module=init_module, depends_on=info_map.required_loads)
        setenvs = data['set']
        prepended_env = data['pre']
        append_env = data['app']

        cmds = []
        field_names = []
        for field_info in fields(cls):
            field_name = field_info.name
            getcmd = field_info.metadata.get('getcmd')
            if getcmd:
                getcmd = getcmd.format(**info_map)
                cmds.append(getcmd)
                field_names.append(field_name)

        # Extra vars that should not be used to populate the KernelData fields
        extra_vars = list(info_map.launcher_args_env_vars)
        # Extra vars needed to resolve the launcher args
        for var in extra_vars:
            cmds.append(f"echo ${var}")

        original_env = os.environ.copy()
        cmd = ' && '.join(cmds)
        try:
            for var, value in prepended_env.items():
                original_value = original_env.get(var, '')
                new_value = os.pathsep.join(filter(None, [value, original_value]))
                original_env[var] = new_value
            for var, value in append_env.items():
                original_value = original_env.get(var, '')
                new_value = os.pathsep.join(filter(None, [original_value, value]))
                original_env[var] = new_value
            output = subprocess.check_output(
                cmd,
                shell=True, executable='/bin/bash',
                stderr=subprocess.STDOUT,
                env={**original_env, **setenvs}
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to load module {module}: {e.output.decode('utf-8')}") from e


        output_lines = output.decode('utf-8').splitlines()
        extra_vars_dct = {}
        try:
            while field_names:
                data_dct[field_names.pop(0)] = output_lines.pop(0)
            while extra_vars:
                extra_vars_dct[extra_vars.pop(0).lower()] = output_lines.pop(0)
        except IndexError as exc:
            raise RuntimeError(
                f"Failed to parse output for module {module}: not enough output lines:\n{output}"
            ) from exc

        data_dct['launcher_args_env_vars'] = extra_vars_dct

        return cls(mod_name=mod_name, mod_version=mod_ver, init_module=init_module, **data_dct)


class EBKernelSpecManager(KernelSpecManager):
    """Custom KernelSpecManager that finds kernels from EasyBuild modules."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.found_specs: dict[str, KernelData] = {}
        self.found_infos: dict[str, ModuleKernelMapping] = {}

    def find_kernel_specs(self):
        """Use the original method to find kernel specs, and then add any `jupyter-server` module kernels.
        (In Easybuild `ipykernel` is installed in the `jupyter-server` bundle)
        """
        specs = super().find_kernel_specs()

        for kernel_name, info_map in MODULE_KERNEL_MAP.items():
            mod_name = info_map.mod_name

            kernel_specs = []
            for init_module in env.get_init_modules():
                for module in module_avail(mod_name, init_module=init_module):
                    found_name, found_ver = module.split('/')
                    if found_name != mod_name:
                        raise RuntimeError(
                            f"Unexpected module name {found_name} for {mod_name} in module_avail() output"
                        )
                    kernel_id = f'{kernel_name}__{found_ver}'

                    data = KernelData.from_env_module(module, info_map, init_module=init_module)

                    current_launcher_version = os.getenv(info_map.launcher_version_env_var, None)
                    current_kernel_version = os.getenv(info_map.kernel_version_env_var, None)

                    min_version, max_version = info_map.launcher_version_filter
                    if min_version and data.launcher_version_sem < min_version:
                        self.log.debug(
                            f"Skipping kernel spec for {module} (Python {data.launcher_version}) as it is below the "
                            f"minimum required version {min_version}"
                        )
                        continue
                    if max_version and data.launcher_version_sem >= max_version:
                        self.log.debug(
                            f"Skipping kernel spec for {module} (Python {data.launcher_version}) as it is above the "
                            f"maximum allowed version {max_version}"
                        )
                        continue

                    # Avoid conflicts for launcher with other externally loaded modules
                    if current_launcher_version and data.launcher_version != current_launcher_version:
                        self.log.debug(
                            f"Skipping kernel spec for {module} (Python {data.launcher_version}) as it does not match "
                            f"current externally loaded Python version {current_launcher_version}"
                        )
                        continue
                    # Avoid conflicts for kernel with other externally loaded modules
                    if current_kernel_version and data.kernel_version != current_kernel_version:
                        self.log.debug(
                            f"Skipping kernel spec for {module} (Kernel version {data.kernel_version}) as it does not "
                            f"match current externally loaded kernel version {current_kernel_version}"
                        )
                        continue
                    kernel_specs.append((kernel_id, data, info_map))

                    self.log.info(
                        f"Found spec for {module} (Launcher: {data.launcher_version}, Kernel: {data.kernel_version})"
                    )

            kernel_display_limit = env.get_kernel_display_limit()
            if kernel_display_limit:
                sorting = env.get_module_sorting()
                reverse = sorting == env.ModuleSorting.DESCENDING
                kernel_specs = list(sorted(kernel_specs, key=lambda x: x[1].launcher_version_sem, reverse=reverse))
                kernel_specs = kernel_specs[:kernel_display_limit]
            for kernel_id, data, info_map in kernel_specs:
                specs[kernel_id] = data.kernel_path
                self.found_specs[kernel_id] = data
                self.found_infos[kernel_id] = info_map

            self.log.info(
                f"Found {len(kernel_specs)} kernel specs for module {mod_name}: {[k[0] for k in kernel_specs]}"
            )

        return specs

    def _get_kernel_spec(self, kernel_id) -> KernelSpec:
        """Get the kernel spec for a given kernel name, using the found_specs dictionary.

        Args:
            kernel_name (str): The name of the kernel to retrieve the spec for.

        Returns:
            KernelSpec: The kernel spec object for the specified kernel name.
        """
        if not self.found_specs:
            self.log.warning('No found_specs available, calling find_kernel_specs()')
            self.find_kernel_specs()

        kernel_data = self.found_specs[kernel_id]
        extra_vars_dct = kernel_data.launcher_args_env_vars
        info_map = self.found_infos[kernel_id]

        launcher_args = info_map.launcher_args

        for var, value in extra_vars_dct.items():
            # if value is None:
            #     raise RuntimeError(f"Failed to get value for {var} from resolving launcher args for module {module}")
            launcher_args = tuple(arg.replace(f"${var.upper()}", value) for arg in info_map.launcher_args)
        prefix = env.get_display_prefix()
        if kernel_data.init_module:
            prefix = ' - '.join(filter(None, (prefix, kernel_data.init_module))) + ' - '
        display_name = info_map.kernel_display_name.format(display_prefix=prefix)
        language = info_map.kernel_language

        launcher_content = STARTUP_TEMPLATE.format(
            module_loads=(
                f"module load {kernel_data.init_module} > /dev/null 2>&1 && "
                f"module load {kernel_data.mod_name}/{kernel_data.mod_version} > /dev/null 2>&1"
            ),
            # kernel_cmd=' '.join((kernel_data.launcher_exe, *launcher_args))
            kernel_cmd=' '.join((info_map.launcher_exec, *launcher_args))
        )
        launcher_script = tempfile.NamedTemporaryFile(  #pylint: disable=consider-using-with
            mode='w', delete=False, prefix='eb_jupyter_kernel_', suffix='.sh'
        )
        launcher_script.write(launcher_content)
        launcher_script.close()
        os.chmod(launcher_script.name, 0o755)

        self.log.info(f"Created launcher script for {kernel_id} at {launcher_script.name}")

        kernel_dct = {
            'argv': [launcher_script.name, '{connection_file}'],
            'display_name': f"{display_name} ({kernel_data.kernel_version})",
            'resource_dir': kernel_data.kernel_path,
            'language': language,
            # 'env': env_dct,
        }

        self.log.debug(f"Creating KernelSpec for {kernel_id}: {kernel_dct}")

        return KernelSpec(**kernel_dct)

    def get_kernel_spec(self, kernel_name) -> KernelSpec:
        """Get the kernel spec for a given kernel name, trying both the superclass method and the custom method."""
        try:
            spec = super().get_kernel_spec(kernel_name)
        except Exception:
            try:
                spec = self._get_kernel_spec(kernel_name)
            except Exception as e:
                self.log.error(f"Failed to get kernel spec for {kernel_name}: {e}")
                raise NoSuchKernel(kernel_name) from e

        return spec
